
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Install ssl certificate for HTTPS and set up reverse proxy
http:
  server_port: 8123
  #ssl_certificate: /ssl/origin.crt
  #ssl_key: /ssl/origin.key
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.4.152   # IP of your reverse proxy
    - 172.16.0.0/12   # (optional) Cloudflare proxy IPs if using Cloudflare Tunnel


# Set external URL
homeassistant:
  external_url: "https://niwotha.katesconsult.com"

# Include definitions for various entities
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Define cameras
#mqtt: !include mqtt.yaml
camera: !include cameras.yaml

# Define shades (covers), display formats for vehicles, weather, etc.
template: !include templates.yaml
input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml

# Configure steve and wallbox APIs and queries
rest_command: !include steve_commands.yaml
#sql: !include steve_queries.yaml

# Initialize logger to debug custom components
logger:
  default: info
  logs:
    custom_components.openweather_forecasts: debug

# Clean up database (home-assistant_v2.db)
recorder:
  purge_keep_days: 7
  auto_purge: true

                        